name: cook_smart
description: "CookSmart is a mobile app for cooking recipes."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  bulleted_list: ^0.0.1+0.1a
  flutter:
    sdk: flutter
  go_router: ^14.6.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0



flutter:
  uses-material-design: true
  assets:
      - assets/
